name: Docker Image CI for GHCR

on: push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: npm install
        run: npm ci
      - name: run the unit tests
        run: npm test
      - name: Publish the image to github container registry
        run: |
          docker login --username gtubbs1414 --password ${{secrets.ACCESS_TOKEN}} ghcr.io
          docker build -t ghcr.io/gtubbs1414/arithmetic-service:1 --file Dockerfile .
          docker push ghcr.io/gtubbs1414/arithmetic-service:1
      - name: Publish the image to azure container registry
        run: |
          docker login --username gtubbspracticum16 --password ${{secrets.AZURE_CONTAINER_REGISTRY}} gtubbspracticum16.azurecr.io
          docker tag ghcr.io/gtubbs1414/arithmetic-service:1 gtubbspracticum16.azurecr.io/arithmetic-service:1
          docker push gtubbspracticum16.azurecr.io/arithmetic-service:1
